server:
  port: 8080
  servlet:
    context-path: /patent
spring:
  datasource:
#    使用的是远程阿里云服务器，自己写上自己的公网ip并配置
    url: jdbc:mysql://localhost:3306/patent?characterEncoding=utf-8&useSSL=false
    username: root
    password: 999999
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.patent.entity.bean
logging:
  level:
    org.thymeleaf: off