server:
  port: 8080
spring:
  # redis配置
  redis:
    mode: single
    host: 47.115.40.50
    port: 6379
    password: 999999
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  #连接池配置
  datasource:
    name: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://47.115.40.50:3306/patent?characterEncoding=utf-8&useSSL=false
      username: root
      password: 999999
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    check-template: true
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
  resources:
    static-locations: [file:E:/IntelliJ IDEA WorkSpace/patent-system/avatarPic,classpath:/resources/,classpath:/META-INF/resources/,classpath:/static/,classpath:/public/]
mybatis-plus:
  dialect: mysql
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.tang.patent.entity.bean
logging:
  level:
    org.thymeleaf: off